AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal VPC Stack

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

Outputs:
  VPCId:
    Description: The ID of the VPC
    Value: !Ref VPC
